# Copyright 2022-2024 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

# A message for registering nodes for Computer Vision algorithms in the application

uint8 REGISTER = 0   # Enum indicating that message type is 'register'
uint8 UNREGISTER = 1 # Enum indicating that message type is 'unregister'

uint8 type       # Enum representing message type (REGISTER/UNREGISTER)
string node_name # Name of the CVNode to associate message with

# Used when registering the node
string prepare_srv_name  # Name of the service for preparing the node
string process_srv_name  # Name of the service for processing the input
string cleanup_srv_name  # Name of the service for cleaning up the node
---
bool status    # Status of the registration/unregistration
string message # Error message if failed
