uint8 REGISTER = 0   # Enum indicating that message type is 'register'
uint8 UNREGISTER = 1 # Enum indicating that message type is 'unregister'

uint8 type       # Enum representing message type (REGISTER/UNREGISTER)
string node_name # Name of the CVNode to associate message with
string srv_name  # Optional name of the service for communication
                 # Used when registering the node
---
bool status    # Status of the registration/unregistration
string message # Error message if failed
