# Copyright 2022-2023 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

# A service representing communication of the ROS 2 node with Kenning using RuntimeProtocol

uint8 message_type  # Message type defined in RuntimeMsgType
byte[] data         # Data attached to the message
---
uint8 message_type  # Message type defined in RuntimeMsgType
byte[] data         # Data attached to the message
