# Copyright 2022-2024 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

# A service representing request for instance segmentation inference on a single frame

VideoFrameMsg   input        # Input image for inference
---
bool            success      # True if inference was successful
SegmentationMsg segmentation # Output segmentations
